// Generated by npm run capture:welcome from measured UI controls.
export const highlights = {
  "project": {
    "x": 2.666666666666667,
    "y": 28.691666666666666,
    "width": 94.66666666666667,
    "height": 22.966666666666665
  },
  "workflow": {
    "x": 50.625,
    "y": 49.89237646947513,
    "width": 22.857142857142858,
    "height": 12.110603874447099
  },
  "run": {
    "x": 55.84415584415584,
    "y": 2.068519715578539,
    "width": 34.87940630797773,
    "height": 8.98513251454428
  },
  "settings": {
    "x": 1.9318181818181817,
    "y": 22.181818181818183,
    "width": 74.54545454545455,
    "height": 22.93181818181818
  }
} as const;
