// Generated by npm run capture:welcome from measured UI controls.
export const highlights = {
  "project": {
    "x": 2.666666666666667,
    "y": 32,
    "width": 94.66666666666667,
    "height": 28.26666666666667
  },
  "workflow": {
    "x": 50.18001800180018,
    "y": 50.0011801080979,
    "width": 23.042304230423042,
    "height": 12.084306922514102
  },
  "run": {
    "x": 53.25670498084292,
    "y": 2.0592020592020592,
    "width": 36.015325670498086,
    "height": 9.60960960960961
  },
  "settings": {
    "x": 2.1,
    "y": 19.52,
    "width": 95.8,
    "height": 20.625
  }
} as const;
