"""Stable Relay limits, identifiers, and public exit codes."""

from typing import Final

APP_NAME: Final = "relay"
SCHEMA_VERSION: Final = 1
RUN_BRANCH_PREFIX: Final = "relay/run/"

EXIT_OK: Final = 0
EXIT_ALREADY_INITIALIZED: Final = 2
EXIT_NOT_A_REPOSITORY: Final = 3
EXIT_UP_CONFIG: Final = 4
EXIT_SUPERVISOR: Final = 5
EXIT_DOCTOR_FAILED: Final = 6
EXIT_PROJECT_NOT_FOUND: Final = 7
EXIT_NOTHING_TO_CLEAN: Final = 8

MAX_LOOP_ITERATIONS: Final = 100
API_MAX_PAGE: Final = 200
API_MAX_PAGE_BYTES: Final = 1_048_576
SSE_MAX_BATCH: Final = 100
SSE_MAX_FRAME_BYTES: Final = 65_536
EVENT_MAX_PAYLOAD_BYTES: Final = 65_536
CONTROL_PAYLOAD_MAX_BYTES: Final = 65_536

DB_BUSY_TIMEOUT_MS: Final = 5_000
REGISTRY_CACHE_TTL_SECONDS: Final = 86_400
REGISTRY_FETCH_TIMEOUT_SECONDS: Final = 10.0
RECONCILE_INTERVAL_SECONDS: Final = 5.0
DISPATCH_ORPHAN_AFTER_SECONDS: Final = 30.0
CONTROL_POLL_INTERVAL_SECONDS: Final = 0.25
CONTROL_REQUEST_TTL_SECONDS: Final = 300.0
ATTEMPT_HEARTBEAT_INTERVAL_SECONDS: Final = 5.0
ATTEMPT_STALE_AFTER_SECONDS: Final = 30.0
INSTANCE_HEARTBEAT_INTERVAL_SECONDS: Final = 5.0
INSTANCE_STALE_AFTER_SECONDS: Final = 30.0
EDITOR_LEASE_TTL_SECONDS: Final = 60.0
SSE_POLL_INTERVAL_SECONDS: Final = 0.5
SHUTDOWN_TIMEOUT_SECONDS: Final = 15.0
CANCELLATION_GRACE_SECONDS: Final = 10.0
MIGRATION_LOCK_STALE_AFTER_SECONDS: Final = 300.0
CLEANUP_BACKOFF_SECONDS: Final = (0.05, 0.2, 0.8)

DEFAULT_HOST: Final = "127.0.0.1"
DEFAULT_PORT: Final = 7845
DEFAULT_WORKERS: Final = 1
DEFAULT_ANTIGRAVITY_PRINT_TIMEOUT_SECONDS: Final = 300
