# Generated by Django 5.2.17 on 2026-09-13 21:13

import uuid

from django.db import migrations, models
from django.db.migrations.operations.base import Operation
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []  # noqa: RUF012

    operations: list[Operation] = [  # noqa: RUF012
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("owner_created", models.BooleanField(default=False)),
                ("settings", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("pid", models.PositiveIntegerField()),
                ("host", models.TextField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("heartbeat_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("shutdown_requested", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="NodeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("terminal", "Terminal"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("worker_id", models.TextField()),
                ("process_pid", models.PositiveIntegerField(blank=True, null=True)),
                ("acp_session_id", models.TextField(blank=True, null=True)),
                (
                    "driver_kind",
                    models.CharField(
                        blank=True,
                        choices=[("acp", "ACP"), ("antigravity", "Antigravity")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("agent_id", models.TextField(blank=True)),
                ("agent_version", models.TextField(blank=True)),
                ("model_value", models.TextField(blank=True)),
                ("config_ids", models.JSONField(default=dict)),
                ("starting_head", models.CharField(max_length=40)),
                ("ending_head", models.CharField(blank=True, max_length=40, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("output_invalid", "Output invalid"),
                            ("timeout", "Timeout"),
                            ("soft_denied", "Soft denied"),
                            ("canceled", "Canceled"),
                            ("worker_lost", "Worker lost"),
                            ("interrupted", "Interrupted"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("error_code", models.TextField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="NodeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope_path", models.TextField()),
                ("parent_scope_path", models.TextField(blank=True, null=True)),
                ("node_id", models.TextField()),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("command", "Command"),
                            ("human_wait", "Human wait"),
                            ("condition", "Condition"),
                            ("loop", "Loop"),
                            ("subworkflow", "Subworkflow"),
                        ],
                        max_length=16,
                    ),
                ),
                ("frozen_def", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("writes", models.BooleanField(default=False)),
                ("selected_branch", models.TextField(blank=True, null=True)),
                ("loop_index", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_path", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                ("git_root", models.TextField()),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("workflow_key", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused_wait", "Paused for input"),
                            ("canceling", "Canceling"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("source_commit", models.CharField(max_length=40)),
                ("run_branch", models.TextField(unique=True)),
                ("worktree_path", models.TextField(unique=True)),
                (
                    "worktree_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("created", "Created"),
                            ("removed", "Removed"),
                            ("cleanup_failed", "Cleanup failed"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "cleanup_policy",
                    models.CharField(
                        choices=[("clean_on_success", "Clean on success"), ("retain", "Retain")],
                        default="clean_on_success",
                        max_length=20,
                    ),
                ),
                ("launcher", models.TextField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.TextField(blank=True, null=True)),
                ("failure_summary", models.TextField(blank=True, null=True)),
                ("entry_point", models.TextField(blank=True, null=True)),
                ("recorded_head", models.CharField(max_length=40)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="relay_web.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentModelObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("agent_id", models.TextField()),
                ("model_value", models.TextField()),
                ("model_name", models.TextField()),
                ("config_id", models.TextField()),
                ("agent_version", models.TextField()),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agent_id", "observed_at"], name="relay_agent_observed_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("declared_name", models.TextField()),
                ("source_path", models.TextField()),
                ("retained_path", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("media_type", models.TextField()),
                ("bytes", models.BigIntegerField()),
                (
                    "preservation_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preserved", "Preserved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="relay_web.nodeattempt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nodeattempt",
            name="node_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="relay_web.noderun",
            ),
        ),
        migrations.CreateModel(
            name="DispatchClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("claim_token", models.CharField(max_length=32, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("dispatched", "Dispatched"),
                            ("claimed", "Claimed"),
                            ("consumed", "Consumed"),
                        ],
                        default="dispatched",
                        max_length=16,
                    ),
                ),
                ("claim_owner", models.TextField(blank=True, null=True)),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_claims",
                        to="relay_web.nodeattempt",
                    ),
                ),
                (
                    "node_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_claims",
                        to="relay_web.noderun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EditorLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("workflow_key", models.TextField()),
                ("holder", models.TextField()),
                ("acquired_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_leases",
                        to="relay_web.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectRelink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("old_path", models.TextField()),
                ("new_path", models.TextField()),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relinks",
                        to="relay_web.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunSnapshot",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="snapshot",
                        serialize=False,
                        to="relay_web.run",
                    ),
                ),
                ("workflow_yaml", models.TextField()),
                ("subworkflows", models.JSONField(default=dict)),
                ("resolved_prompts", models.JSONField(default=list)),
                ("typed_inputs", models.JSONField(default=dict)),
                ("route_table", models.JSONField(default=dict)),
                ("default_model", models.TextField(blank=True)),
                ("agent_prefs", models.JSONField(default=list)),
                ("relay_version", models.TextField()),
                ("runtime_versions", models.JSONField(default=dict)),
                ("hashes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="noderun",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node_runs",
                to="relay_web.run",
            ),
        ),
        migrations.CreateModel(
            name="HumanInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("permission", "Permission"),
                            ("elicitation", "Elicitation"),
                            ("wait", "Wait"),
                        ],
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("expired", "Expired"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="relay_web.nodeattempt",
                    ),
                ),
                (
                    "node_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="relay_web.noderun",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="relay_web.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ts", models.DateTimeField(default=django.utils.timezone.now)),
                ("type", models.TextField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("run", "Run"),
                            ("node", "Node"),
                            ("attempt", "Attempt"),
                            ("agent", "Agent"),
                            ("command", "Command"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("normal", "Normal"), ("redacted", "Redacted")],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="relay_web.nodeattempt",
                    ),
                ),
                (
                    "node_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="relay_web.noderun",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="relay_web.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(choices=[("read", "Read"), ("write", "Write")], max_length=8),
                ),
                ("starting_head", models.CharField(max_length=40)),
                ("recorded_head", models.CharField(max_length=40)),
                ("acquired_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("heartbeat_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_lock",
                        to="relay_web.nodeattempt",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        to="relay_web.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("workflow_key", models.TextField()),
                ("recovery_yaml", models.TextField()),
                ("base_file_hash", models.CharField(max_length=64)),
                (
                    "validation_state",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("unchecked", "Unchecked"),
                        ],
                        default="unchecked",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_drafts",
                        to="relay_web.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("permission_answer", "Permission answer"),
                            ("elicitation_answer", "Elicitation answer"),
                            ("wait_answer", "Wait answer"),
                            ("cancel", "Cancel"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("applied", "Applied"),
                            ("stale", "Stale"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("claim_owner", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_requests",
                        to="relay_web.nodeattempt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "expires_at"], name="relay_control_expiry_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "idempotency_key"), name="relay_unique_control_request"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="nodeattempt",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="relay_attempt_heartbeat_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nodeattempt",
            constraint=models.UniqueConstraint(
                fields=("node_run", "attempt_number"), name="relay_unique_node_attempt"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchclaim",
            index=models.Index(fields=["state", "created_at"], name="relay_dispatch_state_idx"),
        ),
        migrations.AddIndex(
            model_name="editorlease",
            index=models.Index(fields=["expires_at"], name="relay_lease_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="editorlease",
            constraint=models.UniqueConstraint(
                fields=("project", "workflow_key"), name="relay_unique_editor_lease"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["project", "status"], name="relay_run_project_status_idx"),
        ),
        migrations.AddIndex(
            model_name="noderun",
            index=models.Index(fields=["run", "status"], name="relay_node_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="noderun",
            index=models.Index(fields=["run", "parent_scope_path"], name="relay_node_parent_idx"),
        ),
        migrations.AddConstraint(
            model_name="noderun",
            constraint=models.UniqueConstraint(
                fields=("run", "scope_path"), name="relay_unique_node_scope"
            ),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(fields=["run", "id"], name="relay_event_run_id_idx"),
        ),
        migrations.AddIndex(
            model_name="runlock",
            index=models.Index(fields=["run", "mode"], name="relay_run_lock_mode_idx"),
        ),
        migrations.AddConstraint(
            model_name="workflowdraft",
            constraint=models.UniqueConstraint(
                fields=("project", "workflow_key"), name="relay_unique_workflow_draft"
            ),
        ),
    ]
