# Generated by Django 5.2.17 on 2026-09-13

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [  # noqa: RUF012
        ("relay_web", "0001_initial"),
    ]

    operations: list[Operation] = [  # noqa: RUF012
        migrations.AddField(
            model_name="noderun",
            name="outputs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="noderun",
            name="scope_inputs",
            field=models.JSONField(default=dict),
        ),
    ]
