# Generated by Django 5.2.17 on 2026-10-02 17:50

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import StateApps

from relay.constants import API_MAX_PAGE, CONTROL_IDEMPOTENCY_KEY_MAX_CHARS


def index_existing_keys(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Copy retained control keys into the searchable column without changing events."""
    events = apps.get_model("relay_web", "RunEvent")
    manager = events.objects.using(schema_editor.connection.alias)
    for event in manager.filter(payload__has_key="idempotency_key").iterator(
        chunk_size=API_MAX_PAGE
    ):
        payload = getattr(event, "payload", None)
        key = payload.get("idempotency_key") if isinstance(payload, dict) else None
        if isinstance(key, str):
            manager.filter(pk=event.pk).update(idempotency_key=key)


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [  # noqa: RUF012
        ("relay_web", "0002_noderun_runtime_values"),
    ]

    operations: list[Operation] = [  # noqa: RUF012
        migrations.AddField(
            model_name="nodeattempt",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runevent",
            name="idempotency_key",
            field=models.CharField(
                blank=True, max_length=CONTROL_IDEMPOTENCY_KEY_MAX_CHARS, null=True
            ),
        ),
        migrations.RunPython(index_existing_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(
                fields=["run", "type", "idempotency_key"], name="relay_event_control_key_idx"
            ),
        ),
    ]
