# Generated by Django 5.2.17 on 2026-10-05 13:27

from django.db import migrations, models
from django.db.migrations.operations.base import Operation
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [  # noqa: RUF012
        ("relay_web", "0003_scope_deadlines_and_control_keys"),
    ]

    operations: list[Operation] = [  # noqa: RUF012
        migrations.CreateModel(
            name="UsageRetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reset_at", models.DateTimeField(null=True)),
                ("state", models.CharField(default="scheduled", max_length=16)),
                ("error_message", models.TextField(null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.nodeattempt"
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_retry",
                        to="relay_web.run",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "reset_at"], name="relay_usage_retry_due_idx")
                ],
            },
        ),
    ]
