# Generated by Django 5.2.17 on 2026-10-05 14:00

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [  # noqa: RUF012
        ("relay_web", "0004_usage_retries"),
    ]

    operations: list[Operation] = [  # noqa: RUF012
        migrations.AddField(
            model_name="nodeattempt",
            name="process_started",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
