# Generated by Django 5.2.17 on 2026-10-08 17:08

import uuid

from django.db import migrations, models
from django.db.migrations.operations.base import Operation
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [  # noqa: RUF012
        ("relay_web", "0012_run_merge_completion"),
    ]

    operations: list[Operation] = [  # noqa: RUF012
        migrations.CreateModel(
            name="ActionsJobState",
            fields=[
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="relay_web.noderun",
                    ),
                ),
                ("resource", models.JSONField(default=dict)),
                ("accepted_head", models.CharField(blank=True, max_length=40)),
                ("matrix_manifest", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="noderun",
            name="conclusion",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="noderun",
            name="job_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="noderun",
            name="matrix_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noderun",
            name="outcome",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="noderun",
            name="step_id",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="run",
            name="actions_state",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="runsnapshot",
            name="resolved_definition",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="runsnapshot",
            name="semantics_revision",
            field=models.CharField(default="relay-v1", max_length=64),
        ),
        migrations.AlterField(
            model_name="noderun",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("actions_job", "Job"),
                    ("actions_step", "Step"),
                    ("agent", "Agent"),
                    ("command", "Command"),
                    ("human_wait", "Human wait"),
                    ("condition", "Condition"),
                    ("loop", "Loop"),
                    ("subworkflow", "Subworkflow"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ActionsJobLease",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="relay_web.noderun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.TextField()),
                ("name", models.TextField()),
                ("kind", models.CharField(max_length=16)),
                ("value", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=16)),
                ("reference", models.TextField(blank=True)),
                ("revision", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "name", "kind"), name="relay_binding_identity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("workflow_key", models.TextField()),
                ("event", models.TextField()),
                ("enabled", models.BooleanField(default=False)),
                ("allow_writers", models.BooleanField(default=False)),
                ("source_hash", models.CharField(max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("cursor", models.JSONField(default=dict)),
                ("activated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriggerDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurrence", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="relay_web.run"
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.workflowtrigger"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionsArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("manifest", models.JSONField(default=dict)),
                ("directory", models.TextField()),
                ("digest", models.CharField(max_length=64)),
                ("bytes", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.nodeattempt"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.run"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "name"), name="relay_actions_artifact_identity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionsCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.TextField()),
                ("version", models.CharField(max_length=64)),
                ("namespace", models.TextField()),
                ("manifest", models.JSONField(default=dict)),
                ("directory", models.TextField()),
                ("bytes", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accessed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.project"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "key", "version", "namespace"),
                        name="relay_actions_cache_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionsQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scope", models.TextField(default="workflow")),
                ("group", models.TextField()),
                ("mode", models.CharField(default="single", max_length=16)),
                ("cancel_in_progress", models.BooleanField(default=False)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.run"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("run", "scope"), name="relay_queue_identity")
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("approval_required", models.BooleanField(default=False)),
                ("wait_minutes", models.PositiveIntegerField(default=0)),
                ("branches", models.JSONField(default=list)),
                ("url", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="relay_web.project"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"), name="relay_environment_identity"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workflowtrigger",
            constraint=models.UniqueConstraint(
                fields=("project", "workflow_key", "event"), name="relay_trigger_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="triggerdelivery",
            constraint=models.UniqueConstraint(
                fields=("trigger", "occurrence"), name="relay_trigger_occurrence"
            ),
        ),
    ]
