import { expect, test } from "@playwright/test";
import { parse } from "yaml";
import { post } from "./setup-helpers";

test.beforeEach(async ({ page }) => {
  await page.request.get("/api/auth");
  expect((await post(page, "/api/auth/login", { username: "owner", password: "Relay-Test-Passphrase-2026!" })).ok()).toBeTruthy();
  expect((await post(page, "/__test__/reset")).ok()).toBeTruthy();
});
test.afterEach(async ({ page }) => { await post(page, "/__test__/reset"); });

test("global models and thinking defaults save, survive reload, and launch with fresh proof", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1150 });
  await page.goto("/?view=settings");
  await expect(page.getByRole("heading", { name: "Global defaults", exact: true })).toBeVisible();
  const panel = page.getByRole("region", { name: "Global defaults", exact: true });
  await panel.getByRole("combobox", { name: "Add an agent", exact: true }).click();
  await page.getByRole("option", { name: "Codex", exact: true }).click();
  await panel.getByRole("button", { name: /^Codex/ }).click();
  await panel.getByRole("textbox", { name: "Codex exact model" }).fill("m1");
  const configuration = panel.getByRole("region", { name: "Codex configuration", exact: true });
  await expect(configuration.getByRole("combobox", { name: "Thinking effort", exact: true })).toBeEnabled();
  await configuration.getByRole("combobox", { name: "Thinking effort", exact: true }).click();
  await page.getByRole("option", { name: "Low", exact: true }).click();
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("15m");
  await panel.getByRole("combobox", { name: "After a successful run", exact: true }).click();
  await page.getByRole("option", { name: "Keep the working copy", exact: true }).click();
  await panel.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(panel.getByText("Global defaults saved. Future runs inherit these choices.", { exact: true })).toBeVisible();
  await page.reload();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("15m");
  await panel.getByRole("button", { name: /^Codex/ }).click();
  await expect(configuration.getByRole("combobox", { name: "Thinking effort", exact: true })).toHaveText("Low");
  await page.screenshot({ path: info.outputPath("settings-global.png"), fullPage: true, animations: "disabled" });
  const created = await post(page, "/api/workflows", { key: "global-agent", holder: "global-agent", yaml: "name: Global agent\njobs:\n  work:\n    steps:\n      - id: agent\n        uses: relay/agent@v1\n        with: {agent: codex}\n" });
  expect(created.ok(), await created.text()).toBeTruthy();
  const launch = await post(page, "/api/runs", { workflow_key: "global-agent", inputs: {} });
  expect(launch.ok(), await launch.text()).toBeTruthy();
  const { run_id: id } = await launch.json();
  await expect.poll(async () => (await (await page.request.get(`/api/runs/${id}`)).json()).run.status).toBe("succeeded");
  await page.goto(`/?view=runs&run=${id}&job=root.work.agent`);
  await expect(page.getByRole("region", { name: "Job log", exact: true })).toContainText("m1");
  const detail = await (await page.request.get(`/api/runs/${id}`)).json();
  expect(detail.run.cleanup_policy).toBe("retain");
  const events = await (await page.request.get(`/api/runs/${id}/events`)).json();
  expect(JSON.stringify(events)).toContain("effort=low");
  await expect(page.getByText("Advanced data cleanup", { exact: true })).toHaveCount(0);
});

test("project overrides preview inheritance and remove an override without changing global settings", async ({ page }, info) => {
  const current = await (await page.request.get("/api/settings")).json();
  expect((await post(page, "/api/settings", { revision: current.revision, settings: { workflow_defaults: { timeout: "15m", providers: { codex: { model: "m1", effort: "low", permission_mode: "ask" } } } } })).ok()).toBeTruthy();
  await page.goto("/?view=settings");
  await page.getByRole("navigation", { name: "Settings sections" }).getByRole("button", { name: "Project defaults", exact: true }).click();
  const panel = page.getByRole("region", { name: "Project defaults", exact: true });
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("15m");
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toBeDisabled();
  await panel.getByRole("switch", { name: "Override job timeout for this project", exact: true }).check();
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("30m");
  await panel.getByRole("switch", { name: "Override agent models and thinking for this project", exact: true }).check();
  await panel.getByRole("button", { name: /^Codex/ }).click();
  await panel.getByRole("textbox", { name: "Codex exact model", exact: true }).fill("m2");
  const configuration = panel.getByRole("region", { name: "Codex configuration", exact: true });
  const effort = configuration.getByRole("combobox", { name: "Thinking effort", exact: true });
  await expect(effort).toBeEnabled();
  await expect(effort).toHaveText("Agent’s default");
  await expect(configuration.getByRole("combobox", { name: "What the agent may do", exact: true })).toHaveText("Agent’s default");
  await effort.click();
  await page.getByRole("option", { name: "Medium", exact: true }).click();
  await panel.getByRole("button", { name: "Save project defaults", exact: true }).click();
  await expect(panel.getByText("Project defaults saved. Future runs inherit these choices.")).toBeVisible();
  expect((await (await page.request.get("/api/settings")).json()).settings.workflow_defaults.timeout).toBe("15m");
  const effective = (await (await page.request.get("/api/projects/defaults")).json()).effective.workflow_defaults.providers.codex;
  expect(effective).toMatchObject({ model: "m2", effort: "medium", permission_mode: null });
  expect((await (await page.request.get("/api/settings")).json()).settings.workflow_defaults.providers.codex).toMatchObject({ model: "m1", effort: "low" });
  await page.screenshot({ path: info.outputPath("settings-project.png"), fullPage: true, animations: "disabled" });
  await panel.getByRole("switch", { name: "Override job timeout for this project", exact: true }).uncheck();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("15m");
  await panel.getByRole("button", { name: "Save project defaults", exact: true }).click();
  await expect(panel.getByText("Project defaults saved. Future runs inherit these choices.")).toBeVisible();
  expect((await (await page.request.get("/api/projects/defaults")).json()).overrides.workflow_defaults?.timeout).toBeUndefined();
});

test("server settings state their restart requirement and preserve current access", async ({ page }, info) => {
  await page.goto("/?view=settings");
  await page.getByRole("navigation", { name: "Settings sections" }).getByRole("button", { name: "Server and account", exact: true }).click();
  const panel = page.getByRole("region", { name: "Server and account", exact: true });
  await panel.getByRole("spinbutton", { name: "Port", exact: true }).fill("8123");
  await panel.getByRole("spinbutton", { name: "Workers", exact: true }).fill("3");
  await panel.getByRole("switch", { name: "Require login", exact: true }).uncheck();
  await panel.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(panel.getByText("Settings saved. Restart Relay to apply server and login changes.")).toBeVisible();
  await expect(panel.getByText("Signed in as owner. Login is currently required.")).toBeVisible();
  await page.screenshot({ path: info.outputPath("settings-server.png"), fullPage: true, animations: "disabled" });
  await page.reload();
  await page.getByRole("navigation", { name: "Settings sections" }).getByRole("button", { name: "Server and account", exact: true }).click();
  await expect(panel.getByRole("spinbutton", { name: "Port", exact: true })).toHaveValue("8123");
  await expect(panel.getByRole("switch", { name: "Require login", exact: true })).not.toBeChecked();
});

test("validation, conflict, and loading errors retain settings and offer recovery", async ({ page }) => {
  await page.goto("/?view=settings");
  const panel = page.getByRole("region", { name: "Global defaults", exact: true });
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("bad timeout");
  await panel.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(panel.getByRole("alert").filter({ hasText: "Invalid workflow defaults" })).toBeVisible();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("bad timeout");
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("15m");
  const current = await (await page.request.get("/api/settings")).json();
  expect((await post(page, "/api/settings", { revision: current.revision, settings: { port: 8321 } })).ok()).toBeTruthy();
  await panel.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(panel.getByRole("alert").filter({ hasText: "Settings changed in another window" })).toBeVisible();
  await panel.getByRole("button", { name: "Reload settings", exact: true }).click();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("");
  await page.route("**/api/settings", (route) => route.fulfill({ status: 503, json: { code: "persistence_error", message: "Settings could not be read.", context: {} } }));
  await page.reload();
  await expect(page.getByRole("alert").filter({ hasText: "Settings could not be read." })).toBeVisible();
  await page.unroute("**/api/settings");
  await page.getByRole("button", { name: "Retry settings", exact: true }).click();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("");
});

test("storage has no deletion selected, explains retained data, and notification settings are browser scoped", async ({ page }, info) => {
  const created = await post(page, "/__test__/storage-project");
  expect(created.ok()).toBeTruthy();
  const { project_id: id } = await created.json();
  await page.goto(`/?view=settings&project=${id}`);
  await page.getByRole("navigation", { name: "Settings sections" }).getByRole("button", { name: "Storage", exact: true }).click();
  const panel = page.getByRole("region", { name: "Storage", exact: true });
  await expect(panel.getByRole("region", { name: "Project storage" })).toBeVisible();
  await expect(panel.getByRole("button", { name: "Review deletion", exact: true })).toBeDisabled();
  await panel.getByText("About working copies", { exact: true }).click();
  await expect(panel.getByText(/Your repository is not touched/)).toBeVisible();
  const resources = panel.getByRole("region", { name: "Temporary run resources", exact: true });
  await expect(resources.getByText("No completed runs are available for temporary cleanup in this project.")).toBeVisible();
  await expect(resources.getByRole("button", { name: "Retry temporary resource cleanup", exact: true })).toBeDisabled();
  await page.screenshot({ path: info.outputPath("settings-storage.png"), fullPage: true, animations: "disabled" });
  await panel.getByRole("combobox", { name: "Data to delete", exact: true }).click();
  await page.getByRole("option", { name: "Everything for this project", exact: true }).click();
  const review = panel.getByRole("button", { name: "Review deletion", exact: true });
  await review.click();
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("button", { name: "Confirm deletion", exact: true })).toBeDisabled();
  const name = dialog.getByRole("textbox", { name: "Type the project name to confirm", exact: true });
  await expect(name).toBeFocused();
  await name.fill("wrong name");
  await expect(dialog.getByRole("button", { name: "Confirm deletion", exact: true })).toBeDisabled();
  const context = await (await page.request.get(`/api/projects/current?project=${id}`)).json();
  await name.fill(context.project.display_name);
  await expect(dialog.getByRole("button", { name: "Confirm deletion", exact: true })).toBeEnabled();
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(review).toBeFocused();
  await page.getByRole("navigation", { name: "Settings sections" }).getByRole("button", { name: "Notifications", exact: true }).click();
  await expect(page.getByRole("switch", { name: "Desktop notifications", exact: true })).not.toBeChecked();
  await expect(page.getByText("Enabling notifications asks this browser for permission. Other browsers keep their own preference.")).toBeVisible();
});

test("unsaved project overrides survive a global save and narrow settings protect navigation", async ({ page }, info) => {
  await page.setViewportSize({ width: 900, height: 1000 });
  await page.goto("/?view=settings");
  const nav = page.getByRole("navigation", { name: "Settings sections" });
  await nav.getByRole("button", { name: "Project defaults", exact: true }).click();
  const panel = page.getByRole("region", { name: "Project defaults", exact: true });
  await panel.getByRole("switch", { name: "Override job timeout for this project", exact: true }).check();
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("30m");
  await nav.getByRole("button", { name: "Global defaults", exact: true }).click();
  const global = page.getByRole("region", { name: "Global defaults", exact: true });
  await global.getByRole("textbox", { name: "Job timeout", exact: true }).fill("15m");
  await global.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(global.getByText("Global defaults saved. Future runs inherit these choices.")).toBeVisible();
  await nav.getByRole("button", { name: "Project defaults", exact: true }).click();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("30m");
  await page.getByRole("tab", { name: "Workflows", exact: true }).click();
  await expect(page.getByText("Save or discard your settings before leaving.", { exact: true })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: info.outputPath("settings-narrow.png"), fullPage: true, animations: "disabled" });
  await panel.getByRole("button", { name: "Discard changes", exact: true }).click();
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toHaveValue("15m");
  await expect(panel.getByRole("switch", { name: "Override job timeout for this project", exact: true })).not.toBeChecked();
  await page.getByRole("tab", { name: "Workflows", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Project defaults", exact: true })).toHaveCount(0);
});

test("agent discovery failure leaves independent global settings editable", async ({ page }) => {
  await page.route("**/api/agents?**", (route) => route.fulfill({ status: 503, json: { code: "agent_discovery_error", message: "Agent discovery unavailable.", context: {} } }));
  await page.goto("/?view=settings");
  const panel = page.getByRole("region", { name: "Global defaults", exact: true });
  await expect(panel.getByRole("textbox", { name: "Job timeout", exact: true })).toBeEnabled();
  await panel.getByRole("textbox", { name: "Job timeout", exact: true }).fill("15m");
  await panel.getByRole("button", { name: "Save global settings", exact: true }).click();
  await expect(panel.getByText("Global defaults saved. Future runs inherit these choices.")).toBeVisible();
});

test("a job can keep the agent's own defaults despite saved global effort", async ({ page }) => {
  const current = await (await page.request.get("/api/settings")).json();
  expect((await post(page, "/api/settings", { revision: current.revision, settings: { workflow_defaults: { providers: { codex: { model: "m1", effort: "low" } } } } })).ok()).toBeTruthy();
  await page.goto("/?view=workflows&workflow=workflow.yaml");
  await page.locator(".react-flow__node").filter({ hasText: "work" }).click();
  const effort = page.getByRole("region", { name: "Codex configuration", exact: true }).getByRole("combobox", { name: "Effort", exact: true });
  await expect(effort).toHaveText("Use project and global defaults");
  await effort.click();
  await page.getByRole("option", { name: "Agent’s default", exact: true }).click();
  await page.getByRole("button", { name: "Save", exact: true }).click();
  const confirmation = page.getByRole("button", { name: "Save canonical YAML", exact: true });
  if (await confirmation.isVisible()) await confirmation.click();
  await expect(page.getByText("Workflow saved and validated.", { exact: true })).toBeVisible();
  const saved = await (await page.request.get("/api/workflows/workflow")).json();
  expect(parse(saved.yaml).jobs.work.steps[0].with.effort).toBeNull();
  await page.reload();
  await page.locator(".react-flow__node").filter({ hasText: "work" }).click();
  await expect(effort).toHaveText("Agent’s default");
  expect((await post(page, "/__test__/commit")).ok()).toBeTruthy();
  const launched = await post(page, "/api/runs", { workflow_key: "workflow", inputs: {} });
  expect(launched.ok(), await launched.text()).toBeTruthy();
  const { run_id: id } = await launched.json();
  await expect.poll(async () => (await (await page.request.get(`/api/runs/${id}`)).json()).run.status).toBe("succeeded");
  const events = await (await page.request.get(`/api/runs/${id}/events`)).json();
  expect(JSON.stringify(events)).toContain("effort=high");
});
